services:
  - type: web
    name: elite-hub-backend
    env: docker
    repo: https://github.com/Seyllaudrey1312/elite-hub-website.git
    branch: main
    region: oregon
    plan: starter
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: MONGODB_URI
        value: ''
      - key: PORT
        value: ''
      - key: JWT_SECRET
        value: ''
      - key: SMTP_HOST
        value: ''
      - key: SMTP_PORT
        value: '587'
      - key: SMTP_USER
        value: ''
      - key: SMTP_PASS
        value: ''
      - key: ZOOM_API_KEY
        value: ''
      - key: ZOOM_API_SECRET
        value: ''
